# /etc/syslog.conf	Configuration file for inetutils-syslogd.
#
# For more information see syslog.conf(5) manpage.

#
# First some standard logfiles. Log by facility.
#
*.*;auth,authpriv.none		-/var/log/syslog
auth,authpriv.*			/var/log/auth.log
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
cron.*				-/var/log/cron.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log

#
# Logging for the mail system. Split it up so that it is easy to write
# scripts to parse these files.
#
mail.info			-/var/log/mail.info
mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err

#
# Some 'catch-all' logfiles.
#
*.=debug;\
	auth,authpriv.none;\
	news.none;mail.none	-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail,news.none		-/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg				*

#
# Additional files are loaded from "/etc/syslog.d/*.conf". Various example
# configs are provided at /usr/share/doc/inetutils-syslogd/examples/syslog.d/.
#
