#!/bin/sh

set -e

autoreconf -f -i
./configure \
  --disable-libls \
  --disable-servers \
  --disable-clients \
  --enable-ftp \
  --enable-ftpd \
  --enable-ping \
  --enable-ping6 \
  --enable-traceroute \
  # EOL

PATH="/usr/sbin:/sbin:$PATH"

export VERBOSE=1

export FTP=$(command -v inetutils-ftp)
export FTPD=$(command -v ftpd)
export PING6=$(command -v ping6)
export PING=$(command -v ping)
export TRACEROUTE=$(command -v inetutils-traceroute)

make -C lib 2>&1
make -C libinetutils 2>&1
make -C tests check
