#!/bin/sh

set -e

autoreconf -f -i
./configure \
  --disable-libls \
  --disable-talk \
  --disable-ftp \
  --disable-ftpd \
  --disable-ping \
  --disable-ping6 \
  --disable-tftp \
  --disable-tftpd \
  --disable-traceroute \
  # EOL

PATH="/usr/sbin:/sbin:$PATH"

export VERBOSE=1

export DNSDOMAINNAME=$(command -v inetutils-dnsdomainname)
export IFCONFIG=$(command -v inetutils-ifconfig)
export INETD=$(command -v inetutils-inetd)
export LOGGER=$(command -v inetutils-logger)
export SYSLOGD=$(command -v syslogd)
export TELNET=$(command -v inetutils-telnet)
export hostname=$(command -v inetutils-hostname)

make -C lib 2>&1
make -C libinetutils 2>&1
make -C tests check
