.\" Copyright © 2015 Free Software Foundation, Inc.
.\" License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.\"
.\" This is free software: you are free to change and redistribute it.
.\" There is NO WARRANTY, to the extent permitted by law.
.Dd February 1, 2019
.Dt DNSDOMAINNAME 1 URM
.Os "GNU Network Utilities"
.Sh NAME
.Nm dnsdomainname
.Nd show DNS domain name
.Sh SYNOPSIS
.Nm dnsdomainname
.Op Ar option ...
.Sh DESCRIPTION
Show the domain part of the system's fully qualified host name.
.Pp
The tool uses
.Xr gethostname 2
to get the host name of the system and
.Xr getaddrinfo 2
to resolve it into a canonical name.
The part after the first period
.Pq Sq \&.
of the canonical name is shown.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl ? , -help
Give this help list.
.It Fl -usage
Give a short usage message.
.It Fl V , -version
Print program version.
.El
.Sh SEE ALSO
.Xr gethostname 2 ,
.Xr getaddrinfo 3
