.\" Copyright © 2015 Free Software Foundation, Inc.
.\" License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.\"
.\" This is free software: you are free to change and redistribute it.
.\" There is NO WARRANTY, to the extent permitted by law.
.Dd February 1, 2019
.Dt HOSTNAME 1 URM
.Os "GNU Network Utilities"
.Sh NAME
.Nm hostname
.Nd show or set the system host name
.Sh SYNOPSIS
.Nm hostname
.Op Ar option ...
.Op Ar name
.Sh DESCRIPTION
Show the system's host name, or set it if
.Ar name
is specified.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a , -aliases
Also show aliases for the host name.
.It Fl d , -domain
Show the DNS domain name.
.It Fl f , -fqdn , -long
Show the DNS host name or FQDN.
.It Fl F , -file Ar file
Set the host name or NIS domain name from
.Ar file .
.It Fl i , -ip-addresses
Show the addresses for the host name.
.It Fl s , -short
Show the short host name.
.It Fl y , -yp , -nis
Show the NIS/YP domain name.
.It Fl ? , -help
Give this help list.
.It Fl -usage
Give a short usage message.
.It Fl V , -version
Print program version.
.El
