.\" Copyright © 2015 Free Software Foundation, Inc.
.\" License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.\"
.\" This is free software: you are free to change and redistribute it.
.\" There is NO WARRANTY, to the extent permitted by law.
.Dd February 9, 2019
.Dt IFCONFIG 1 URM
.Os "GNU Network Utilities"
.Sh NAME
.Nm ifconfig
.Nd configure network interfaces
.Sh SYNOPSIS
.Nm ifconfig
.Op Ar option ...
.Ar name
.Op Ar addr
.Op Cm broadcast Ar brdaddr
.Op Cm { pointopoint | dstaddr } Ar dstaddr
.Op Cm netmask Ar mask
.Op Cm { ether | hwaddr | lladdr } Ar macaddr
.Op Cm metric Ar n
.Op Cm mtu Ar n
.Op Cm txqueuelen Ar n
.Op Cm up | down
.Op Ar flags
.Sh DESCRIPTION
Configure network interfaces.
.Pp
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.Pp
Known flags are:
.Cm allmulti , arp , automedia , broadcast , debug , dynamic , master ,
.Cm multicast , pointopoint , portsel , promisc , slave , trailers , up .
Prepending
.Cm no
to any of these flags will negate their effect.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a , -all
Display all available interfaces.
.It Fl A , -address Ar addr
Set the interface address to
.Ar addr .
.It Fl B , -broadcast Ar addr
.It Fl b , -brdaddr Ar addr
Set the broadcast address to
.Ar addr .
.It Fl d , -dstaddr Ar addr
.It Fl p , -peer Ar addr
Set the destination (peer) address to
.Ar addr .
.It Fl -up
Activate the interface (default if address is given).
.It Fl -down
Shut the interface down.
.It Fl F , -flags Ar flag , Ns Op Ar flag ...
Set the interface flags.
.It Fl i , -interface Ar name
Configure the network interface
.Ar name .
.It Fl l , -list
List the available or selected interfaces.
.It Fl m , -netmask Ar mask
Set the netmask to
.Ar mask .
.It Fl -metric Ar n
Set the interface metric to
.Ar n .
.It Fl M , -mtu Ar n
Set the interface MTU to
.Ar n .
.It Fl -format Ar format
Select the output format; set to
.Cm help
for information.
.It Fl s , -short
Short output format.
.It Fl v , -verbose
Output information when configuring the interface.
.It Fl ? , -help
Give this help list.
.It Fl -usage
Give a short usage message.
.It Fl V , -version
Print program version.
.El
.Pp
Linux\-specific options:
.Bl -tag -width Ds
.It Fl T , -txqlen Ar n
Set the transmit queue length to
.Ar n .
.El
