.\" Copyright © 2015-2019 Free Software Foundation, Inc.
.\" License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.\"
.\" This is free software: you are free to change and redistribute it.
.\" There is NO WARRANTY, to the extent permitted by law.
.Dd February 9, 2019
.Dt PING6 1 URM
.Os "GNU Network Utilities"
.Sh NAME
.Nm ping6
.Nd send
.Tn ICMP6 ECHO_REQUEST
packets to network hosts
.Sh SYNOPSIS
.Nm ping6
.Op Ar option ...
.Ar host ...
.Sh DESCRIPTION
Send
.Tn ICMP6 ECHO_REQUEST
packets to network hosts.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c , -count Ar number
Stop after sending
.Ar number
packets.
.It Fl i , -interval Ar number
Wait
.Ar number
seconds between sending each packet.
.It Fl w , -timeout Ar n
Stop after
.Ar n
seconds.
.It Fl n , -numeric
Do not resolve host addresses.
.It Fl -hoplimit Ar n
.It Fl -ttl Ar n
Specify
.Ar n
as hop-limit.
.It Fl r , -ignore-routing
Send directly to a host on an attached network.
.It Fl T , -tos Ar n
Set traffic class to
.Ar n .
.It Fl f , -flood
Flood ping (root only).
.It Fl l , -preload Ar number
Send
.Ar number
packets as fast as possible before falling into normal mode
of behavior (root only).
.It Fl p , -pattern Ar pattern
Fill ICMP6 packet with the given
.Ar pattern
(hex).
.It Fl s , -size Ar number
Send
.Ar number
data octets.
.It Fl v , -verbose
Verbose output.
.It Fl q , -quiet
Quiet output.
.It Fl d , -debug
Set the
.Dv SO_DEBUG
option.
.It Fl ? , -help
Give this help list.
.It Fl -usage
Give a short usage message.
.It Fl V , -version
Print program version.
.El
.Pp
Options marked with (root only) are available only to superuser.
