.\" Copyright © 2015-2019 Free Software Foundation, Inc.
.\" License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.\"
.\" This is free software: you are free to change and redistribute it.
.\" There is NO WARRANTY, to the extent permitted by law.
.Dd February 9, 2019
.Dt TRACEROUTE 1 URM
.Os "GNU Network Utilities"
.Sh NAME
.Nm traceroute
.Nd trace the route to a host
.Sh SYNOPSIS
.Nm traceroute
.Op Ar option ...
.Ar host
.Sh DESCRIPTION
Print the route packets trace to network
.Ar host .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f , -first-hop Ns = Ns Ar start
Set the initial hop distance, that is the time-to-live.
.It Fl g , -gateways Ns = Ns Ar gates
List of gateways for loose source routing.
.It Fl I , -icmp
Use ICMP ECHO as probe.
.It Fl m , -max-hop Ns = Ns Ar num
Set the maximal hop count (default is 64).
.It Fl M , -type Ns = Ns Ar method
Use the
.Ar method
.Cm ( icmp
or the default
.Cm udp )
for traceroute operations.
.It Fl p , -port Ns = Ns Ar port
Use the destination
.Ar port
port (default is 33434).
.It Fl q , -tries Ns = Ns Ar num
Send
.Ar num
probe packets per hop (default is 3).
.It Fl -resolve-hostnames
Resolve hostnames.
.It Fl t , -tos Ns = Ns Ar class
Set the type of service (TOS) to
.Ar class .
.It Fl w , -wait Ns = Ns Ar timeout
Wait
.Ar timeout
seconds for responses (default is 3).
.It Fl ? , -help
Give this help list.
.It Fl -usage
Give a short usage message.
.It Fl V , -version
Print program version.
.El
