.TH TRACEROUTE "1" "2019-02-09" "GNU inetutils" "User Commands"
.SH NAME
traceroute \- Trace the route to a host
.SH SYNOPSIS
.B traceroute
[\fIoption\fR...] \fIhost\fR
.SH DESCRIPTION
Print the route packets trace to network \fIhost\fP.
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-first\-hop\fR=\fInum\fR
Set initial hop distance, that is the time-to-live.
.TP
\fB\-g\fR, \fB\-\-gateways\fR=\fIgates\fR
List of gateways for loose source routing.
.TP
\fB\-I\fR, \fB\-\-icmp\fR
Use ICMP ECHO as probe.
.TP
\fB\-m\fR, \fB\-\-max\-hop\fR=\fInum\fR
Set maximal hop count (default is \fB64\fP).
.TP
\fB\-M\fR, \fB\-\-type\fR=\fImethod\fR
Use \fImethod\fP (\fBicmp\fP or \fBudp\fP) for traceroute operations,
defaulting to \fBudp\fP.
.TP
\fB\-p\fR, \fB\-\-port\fR=\fIport\fR
Use destination \fIport\fP port (default is \fB33434\fP).
.TP
\fB\-q\fR, \fB\-\-tries\fR=\fInum\fR
Send \fInum\fP probe packets per hop (default is \fB3\fP).
.TP
\fB\-\-resolve\-hostnames\fR
Resolve hostnames.
.TP
\fB\-t\fR, \fB\-\-tos\fR=\fInum\fR
Set type of service (TOS) to \fInum\fP.
.TP
\fB\-w\fR, \fB\-\-wait\fR=\fInum\fR
Wait \fInum\fP seconds for response (default is \fB3\fP).
.TP
\fB\-?\fP, \fB\-\-help\fR
Give this help list.
.TP
\fB\-\-usage\fR
Give a short usage message.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
