#! /bin/sh -e

# Prerm for inetutils-inetd

# XXX: Workaround for bug in 2:1.4.2+20030703-4 and -7

if [ "$1" = "failed-upgrade" -a \
     \( "$2" = "2:1.4.2+20030703-4" -o \
        "$2" = "2:1.4.2+20030703-5" -o \
        "$2" = "2:1.4.2+20030703-6" -o \
        "$2" = "2:1.4.2+20030703-7" \) ]
then
  pidfile=/PATH_INETDPID

  start-stop-daemon --stop --quiet --oknodo --pidfile $pidfile \
	--exec /usr/sbin/inetd

  if [ -e $pidfile ]; then
    rm -f $pidfile
  fi

  exit 0
fi

#DEBHELPER#

