# /etc/syslog.d/tty.conf	Configuration file for inetutils-syslogd.
#
# For more information see syslog.conf(5) manpage.

#
# Display messages on a console (say, on a virtual console left idle).
#
daemon,mail.*;\
	*.=debug;*.=info;\
	*.=notice;*.=warn	/dev/tty8
