# /etc/syslog.d/xconsole.conf	Configuration file for inetutils-syslogd.
#
# For more information see syslog.conf(5) manpage.

#
# The named pipe /run/xconsole is for the 'xconsole' utility. To use it,
# you must invoke 'xconsole' with the '-file' option:
#
#    $ xconsole -file /run/xconsole [...]
#
# NOTE: Adjust the selector below, or you might get overwhelmed on busy sites.
#
daemon.*;mail.*;\
	*.=debug;*.=info;\
	*.=notice;*.=warn	|/run/xconsole
